services:
  nginx:
    image: nginx:alpine
    hostname: myhost.local
    healthcheck:
      test: ["CMD", "curl", "-f", "https://myhost.local"]
      timeout: 10s
      retries: 3
      start_period: 2s
      start_interval: 1s
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - ./certs:/certs
      - type: image
        source: laurentgoderre689/certs:debian
        target: /etc/ssl/certs/

  test:
    image: alpine
    command: ["wget", "-O", "-", "https://myhost.local"]
    depends_on:
      nginx:
        condition: service_healthy
    volumes:
      - type: image
        source: laurentgoderre689/certs:debian
        target: /etc/ssl/certs/

configs:
  nginx_config:
    content: |
      server {
        listen 80 default_server;
        server_name _;
        return 301 https://$$host$$request_uri;
      }

      server {
        listen              443 ssl;
        server_name         myhost.local;

        ssl_certificate     /certs/myhost.local.crt;
        ssl_certificate_key /certs/myhost.local.key;
        ssl_protocols       TLSv1.2 TLSv1.3;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
      }
